In [1]:
import numpy as np
import pandas as pd

In [1]:
print(a)

SyntaxError: can't use starred expression here (97816009.py, line 4)

In [6]:
np.random.seed(1)

In [7]:
list(np.random.choice([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20], size=3, replace=False))

[4, 17, 7]

In [9]:
np.random.seed(1)

In [18]:
list(np.random.choice([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20], size=3, replace=False))

[12, 15, 4]

In [1]:
import test_a
import test_b

In [2]:
import numpy as np

np.random.seed(1)

In [3]:
test_a.get_list()

[4, 17, 7]

In [4]:
test_b.get_list()

[16, 9, 17]

In [5]:
list(np.random.choice([1,2,3,4,5,6], size=3, replace=False))

[6, 3, 4]

In [3]:
np.random.choice([1,2,3,4,5,6], size=3, replace=False)

array([2, 4, 5])

In [4]:
np.random.choice([1,2,3,4,5,6], size=3, replace=False)

array([4, 6, 2])

In [2]:
tmp_table = []
for i in range(1000):
    tmp_table.append(np.random.choice([1,2,3,4,5,6], size=6, replace=True))

a = np.array(tmp_table)
a_pd = pd.DataFrame(a, columns=["a", "b", "c", "d", "e", "f"])

In [3]:
a_pd

a  b  c  d  e  f
0    3  1  4  1  6  5
1    6  2  1  6  5  5
2    4  3  2  6  3  4
3    2  4  4  3  6  4
4    6  2  1  1  6  3
..  .. .. .. .. .. ..
995  6  2  3  6  2  4
996  3  4  2  5  6  2
997  3  4  5  5  1  5
998  5  2  4  1  2  6
999  5  1  3  6  2  6

[1000 rows x 6 columns]

In [4]:
import new_scripts.bagging_utils as bu

In [5]:
fb = bu.FeatureBagger()

new_scripts.bagging_utils.FeatureBagger

In [16]:
fb = fb.fit(a_pd)

In [25]:
cols = [["a", "b", "c", "d", "e", "f"][i] for i in fb.subset]
list(zip(fb.subset, cols))

[(2, 'c'), (3, 'd'), (5, 'f')]

In [27]:
ll_pd = fb.transform(a_pd.to_numpy())
ll_pd = pd.DataFrame(ll_pd, columns=cols)

In [28]:
ll_pd

c  d  f
0    2  6  4
1    2  3  4
2    5  1  5
3    5  1  2
4    6  2  4
..  .. .. ..
995  4  5  1
996  4  2  4
997  6  6  5
998  2  5  5
999  2  6  3

[1000 rows x 3 columns]

In [19]:
a_pd

a  b  c  d  e  f
0    6  3  2  6  3  4
1    2  2  2  3  3  4
2    6  5  5  1  3  5
3    4  5  5  1  4  2
4    6  4  6  2  5  4
..  .. .. .. .. .. ..
995  6  3  4  5  5  1
996  1  4  4  2  6  4
997  5  2  6  6  6  5
998  6  1  2  5  4  5
999  1  6  2  6  4  3

[1000 rows x 6 columns]

In [20]:
ll_pd

array([[2, 6, 4],
       [2, 3, 4],
       [5, 1, 5],
       ...,
       [6, 6, 5],
       [2, 5, 5],
       [2, 6, 3]])

In [6]:
def func_a(a):
    print(a)
def func_b(a,b):
    print(a)
    print(b)
def func_c(a,b,c):
    print(a)
    print(b)
    print(c)

aaa = [(func_a, ()), (func_b, (2,)), (func_c, (2,3))]

In [7]:
for func, arg in aaa:
    print(arg)

()
(2,)
(2, 3)


In [10]:
for func, arg in aaa:
    print(1,*arg)

1
1 2
1 2 3


In [9]:
for func, arg in aaa:
    print(f"Running {func.__name__}...")
    if len(arg)==0:
        func(1)
    else:
        func(1,*arg)

Running func_a...
1
Running func_b...
1
2
Running func_c...
1
2
3
